apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deployment.labels.appName }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.appName }}
  template:
    metadata:
      annotations: {}
      labels:
        app: {{ .Values.deployment.labels.appName }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: "{{ .Values.deployment.image.name }}:{{ .Values.deployment.image.version }}"
          imagePullPolicy: {{ .Values.deployment.image.imagePullPolicy }}
          args: {{ toJson .Values.deployment.container.args }}
          ports:
            - containerPort: {{ .Values.deployment.container.portNumber }}
              name: {{ .Values.deployment.container.name }}
          resources:
            requests:
              nvidia.com/gpu: {{ .Values.deployment.resources.requests.gpu }}
              memory: {{ .Values.deployment.resources.requests.memory }}
            limits:
              nvidia.com/gpu: {{ .Values.deployment.resources.limits.gpu }}
              memory: {{ .Values.deployment.resources.limits.memory }}
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
